app = "bulgaria-avalanche-report"
primary_region = "otp"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  AVALANCHE_REPORT = """
    data_dir="/data-volume"
    listen_address="[::]:8080"
    base_url="https://bulgaria-avalanche-report.fly.dev/"
    default_language_order=["bg-BG", "en-UK"]
    forecast_spreadsheet_schema="forecast_spreadsheet_schema.bansko.0.3.1.json"

    [templates]
    directory="templates"

    [i18n]
    directory="i18n"

    [map]
    source="OpenTopoMap"

    [weather_maps.Windy]
    latitude=41.753
    longitude=23.432

    [weather_maps.Meteoblue]
    location_id="todorka-summit_bulgaria_726427"
  """

[[mounts]]
  source = "bulgaria_avalanche_report_data"
  destination = "/data-volume"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
